### ISSUE TITLE
[lcc_members] crash when invoice is created

### ISSUE THREAD

**Issue by guigeek208** [Lokavaluto/lokavaluto-addons#98]
When a membership is activated on a user and the invoice is created, i have a crash :

Erreur:
Odoo Server Error

Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/odoo/api.py", line 1049, in get
value = self._data[key][field][record._ids[0]]
KeyError: 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1064, in get
value = record.env.cache.get(record, self)
File "/opt/odoo/custom/src/odoo/odoo/api.py", line 1051, in get
raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(7,).membership_state', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 98, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in call
return self.method(*args, **kw)
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
response = f(*args, **kw)
File "/opt/odoo/auto/addons/web/controllers/main.py", line 967, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/odoo/auto/addons/web/controllers/main.py", line 955, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/opt/odoo/auto/addons/membership/wizard/membership_invoice.py", line 29, in membership_invoice
invoice_list = self.env['res.partner'].browse(self._context.get('active_ids')).create_membership_invoice(datas=datas)
File "/opt/odoo/auto/addons/membership/models/partner.py", line 203, in create_membership_invoice
invoice.write({'invoice_line_ids': [(0, 0, line_values)]})
File "/opt/odoo/auto/addons/membership/models/account_invoice.py", line 34, in write
return super(Invoice, self).write(vals)
File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 321, in write
result = super(MailThread, self).write(values)
File "/opt/odoo/auto/addons/mail/models/mail_activity.py", line 621, in write
return super(MailActivityMixin, self).write(vals)
File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3401, in write
self.recompute()
File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5322, in recompute
vals = {n: rec[n] for n in ns}
File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5322, in <dictcomp>
vals = {n: rec[n] for n in ns}
File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5169, in getitem
return self._fields[key].__get__(self, type(self))
File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1068, in get
self.determine_value(record)
File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1157, in determine_value
self.compute_value(recs)
File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1135, in compute_value
self._compute_value(records)
File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1126, in _compute_value
getattr(records, self.compute)()
File "/opt/odoo/auto/addons/membership/models/partner.py", line 49, in _compute_membership_state
values = self._membership_state()
File "/opt/odoo/auto/addons/lcc_members/models/res_partner.py", line 148, in _membership_state
if (mline.date_to) >= today and (mline.date_from) <= today:
TypeError: '>=' not supported between instances of 'bool' and 'datetime.date'

**Comment by njeudy** [comment]
Hello, ok will check this. I think your membership product have no date_from and date_to .. will catch this with usererror

**Comment by MatSarr** [comment]
solved
